# https://www.appveyor.com/docs/appveyor-yml

install:
  # Download and install a minimal TeX Live, based on
  # https://github.com/latex3/latex3/blob/master/support/texlive.sh.
  - ps: Start-FileDownload 'http://mirror.ctan.org/systems/texlive/tlnet/install-tl.zip'
  - 7z x install-tl.zip
  - cd install-tl-20*
  # The install-tl-windows.bat script contains pause commands that stop
  # execution until a key is pressed. Remove these.
  - ps: Set-Content install-tl-windows.bat (Get-Content install-tl-windows.bat | Select-String -Pattern '^pause$' -NotMatch)
  - ps: Set-Content texlive.profile "selected_scheme scheme-minimal`nTEXDIR C:\texlive`noption_doc 0`noption_src 0`n"
  - install-tl-windows -no-gui -profile=texlive.profile
  - cd ..
  - set PATH=%PATH%;C:\texlive\bin\win32
  # Install packages required to create cross-and-crescent.sty and
  # crossAndCrescent.asy.
  - tlmgr install
    fontspec
    graphics
    hyperref
    latex-bin
    luaotfload
    oberdiek
    pgf
    url
    xcolor
  # Install packages required to test cross-and-crescent.sty and
  # crossAndCrescent.asy.
  - tlmgr install
    asymptote
    standalone

build_script:
  - ps: ForEach ($i in 1..2) { lualatex -interaction=batchmode cross-and-crescent.dtx }
  - ps: latex -jobname logo -output-format pdf '\documentclass{standalone}\usepackage{cross-and-crescent}\begin{document}\crossAndCrescent\end{document}'
  - ps: asy -outformat pdf -outname logo.pdf -noView -command 'include crossAndCrescent; draw(crossAndCrescentPath());'

  - del cross-and-crescent.sty crossAndCrescent.asy

  - for /l %%G in (1, 1, 2) do lualatex -interaction=batchmode cross-and-crescent.dtx
  - latex -interaction batchmode -jobname logo -output-format pdf "\documentclass{standalone}\usepackage{cross-and-crescent}\begin{document}\crossAndCrescent\end{document}"
  - asy -outformat pdf -outname logo.pdf -noView -command "include crossAndCrescent; draw(crossAndCrescentPath());"

test: off

artifacts:
  - path: cross-and-crescent.pdf
  - path: cross-and-crescent.sty
  - path: crossAndCrescent.asy

skip_tags: true

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
